/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import java.awt.Color;

/**
 *
 * @author Jeffrey Leiva
 */
public class FrameFinalAccount extends javax.swing.JFrame {

    /**
     * Creates new form FrameFinalAccount
     */
    int xMouse,yMouse;
    public FrameFinalAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        optionHeaderPanel = new javax.swing.JPanel();
        pointTxt = new javax.swing.JLabel();
        questionTxt = new javax.swing.JLabel();
        accountSettingsTxt = new javax.swing.JLabel();
        optionLateralPanel = new javax.swing.JPanel();
        generalInfoPanel = new javax.swing.JPanel();
        generalInfoTxt = new javax.swing.JLabel();
        securityInfoPanel = new javax.swing.JPanel();
        securityTxt = new javax.swing.JLabel();
        devicePanel = new javax.swing.JPanel();
        deviceTxt = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        passTxt = new javax.swing.JLabel();
        organizationPanel = new javax.swing.JPanel();
        organizationTxt = new javax.swing.JLabel();
        configPanel = new javax.swing.JPanel();
        configTxt = new javax.swing.JLabel();
        sessionPanel = new javax.swing.JPanel();
        sessionTxt = new javax.swing.JLabel();
        applicationPanel = new javax.swing.JPanel();
        appTxt = new javax.swing.JLabel();
        subPanel = new javax.swing.JPanel();
        subTxt = new javax.swing.JLabel();
        scrollOnePane = new javax.swing.JScrollPane();
        insideScrollPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profileTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(102, 102, 102));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 844, Short.MAX_VALUE)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 50));

        pointTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        pointTxt.setForeground(new java.awt.Color(102, 102, 102));
        pointTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pointTxt.setText("o o o");

        questionTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        questionTxt.setForeground(new java.awt.Color(102, 102, 102));
        questionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionTxt.setText("?");

        accountSettingsTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        accountSettingsTxt.setForeground(new java.awt.Color(102, 102, 102));
        accountSettingsTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountSettingsTxt.setText("L");

        javax.swing.GroupLayout optionHeaderPanelLayout = new javax.swing.GroupLayout(optionHeaderPanel);
        optionHeaderPanel.setLayout(optionHeaderPanelLayout);
        optionHeaderPanelLayout.setHorizontalGroup(
            optionHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionHeaderPanelLayout.createSequentialGroup()
                .addContainerGap(711, Short.MAX_VALUE)
                .addComponent(pointTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountSettingsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        optionHeaderPanelLayout.setVerticalGroup(
            optionHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(questionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(accountSettingsTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(optionHeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 910, 50));

        optionLateralPanel.setBackground(new java.awt.Color(255, 255, 255));

        generalInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        generalInfoPanel.setForeground(new java.awt.Color(255, 255, 255));
        generalInfoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generalInfoPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generalInfoPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generalInfoPanelMouseExited(evt);
            }
        });

        generalInfoTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        generalInfoTxt.setForeground(new java.awt.Color(102, 102, 102));
        generalInfoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generalInfoTxt.setText("Información general");
        generalInfoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generalInfoTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generalInfoTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout generalInfoPanelLayout = new javax.swing.GroupLayout(generalInfoPanel);
        generalInfoPanel.setLayout(generalInfoPanelLayout);
        generalInfoPanelLayout.setHorizontalGroup(
            generalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalInfoPanelLayout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(generalInfoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        generalInfoPanelLayout.setVerticalGroup(
            generalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generalInfoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        securityInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        securityInfoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                securityInfoPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                securityInfoPanelMouseExited(evt);
            }
        });

        securityTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        securityTxt.setForeground(new java.awt.Color(102, 102, 102));
        securityTxt.setText("Información de seguridad");

        javax.swing.GroupLayout securityInfoPanelLayout = new javax.swing.GroupLayout(securityInfoPanel);
        securityInfoPanel.setLayout(securityInfoPanelLayout);
        securityInfoPanelLayout.setHorizontalGroup(
            securityInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, securityInfoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(securityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        securityInfoPanelLayout.setVerticalGroup(
            securityInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(securityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        devicePanel.setBackground(new java.awt.Color(255, 255, 255));
        devicePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                devicePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                devicePanelMouseExited(evt);
            }
        });

        deviceTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        deviceTxt.setForeground(new java.awt.Color(102, 102, 102));
        deviceTxt.setText("Dispositivos");
        deviceTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout devicePanelLayout = new javax.swing.GroupLayout(devicePanel);
        devicePanel.setLayout(devicePanelLayout);
        devicePanelLayout.setHorizontalGroup(
            devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devicePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deviceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        devicePanelLayout.setVerticalGroup(
            devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deviceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        passwordPanel.setBackground(new java.awt.Color(255, 255, 255));
        passwordPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordPanelMousePressed(evt);
            }
        });

        passTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        passTxt.setForeground(new java.awt.Color(102, 102, 102));
        passTxt.setText("Contraseñas");
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        organizationPanel.setBackground(new java.awt.Color(255, 255, 255));
        organizationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                organizationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                organizationPanelMouseExited(evt);
            }
        });

        organizationTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        organizationTxt.setForeground(new java.awt.Color(102, 102, 102));
        organizationTxt.setText("Organizaciones");

        javax.swing.GroupLayout organizationPanelLayout = new javax.swing.GroupLayout(organizationPanel);
        organizationPanel.setLayout(organizationPanelLayout);
        organizationPanelLayout.setHorizontalGroup(
            organizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, organizationPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(organizationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        organizationPanelLayout.setVerticalGroup(
            organizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(organizationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        configPanel.setBackground(new java.awt.Color(255, 255, 255));
        configPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configPanelMouseExited(evt);
            }
        });

        configTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        configTxt.setForeground(new java.awt.Color(102, 102, 102));
        configTxt.setText("Configuración y privacidad");

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(configTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        sessionPanel.setBackground(new java.awt.Color(255, 255, 255));
        sessionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sessionPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sessionPanelMouseExited(evt);
            }
        });

        sessionTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        sessionTxt.setForeground(new java.awt.Color(102, 102, 102));
        sessionTxt.setText("Mis inicios de sesión");

        javax.swing.GroupLayout sessionPanelLayout = new javax.swing.GroupLayout(sessionPanel);
        sessionPanel.setLayout(sessionPanelLayout);
        sessionPanelLayout.setHorizontalGroup(
            sessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sessionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sessionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sessionPanelLayout.setVerticalGroup(
            sessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sessionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        applicationPanel.setBackground(new java.awt.Color(255, 255, 255));
        applicationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applicationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applicationPanelMouseExited(evt);
            }
        });

        appTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        appTxt.setForeground(new java.awt.Color(102, 102, 102));
        appTxt.setText("Aplicaciones de Office");

        javax.swing.GroupLayout applicationPanelLayout = new javax.swing.GroupLayout(applicationPanel);
        applicationPanel.setLayout(applicationPanelLayout);
        applicationPanelLayout.setHorizontalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, applicationPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(appTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        applicationPanelLayout.setVerticalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        subPanel.setBackground(new java.awt.Color(255, 255, 255));
        subPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subPanelMouseExited(evt);
            }
        });

        subTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        subTxt.setForeground(new java.awt.Color(102, 102, 102));
        subTxt.setText("Suscripciones");

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(subTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout optionLateralPanelLayout = new javax.swing.GroupLayout(optionLateralPanel);
        optionLateralPanel.setLayout(optionLateralPanelLayout);
        optionLateralPanelLayout.setHorizontalGroup(
            optionLateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generalInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(securityInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(devicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(organizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(configPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sessionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(applicationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        optionLateralPanelLayout.setVerticalGroup(
            optionLateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionLateralPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(generalInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(devicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organizationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sessionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applicationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        bg.add(optionLateralPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 600));

        scrollOnePane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        insideScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Información de seguridad");

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        textArea.setRows(5);
        textArea.setText(" Mantenga actualizados los\n métodos de comprobación y \n la información de seguridad");
        textArea.setBorder(null);
        jScrollPane1.setViewportView(textArea);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 120, 212));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar información");

        javax.swing.GroupLayout insideScrollPaneLayout = new javax.swing.GroupLayout(insideScrollPane);
        insideScrollPane.setLayout(insideScrollPaneLayout);
        insideScrollPaneLayout.setHorizontalGroup(
            insideScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insideScrollPaneLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(insideScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insideScrollPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insideScrollPaneLayout.createSequentialGroup()
                        .addGroup(insideScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        insideScrollPaneLayout.setVerticalGroup(
            insideScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insideScrollPaneLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        scrollOnePane.setViewportView(insideScrollPane);

        bg.add(scrollOnePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 300, 280));

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));
        profilePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        profileTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        profileTxt.setForeground(new java.awt.Color(102, 102, 102));
        profileTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileTxt.setText("Jeffrey Daniel Leiva Cascante");

        emailTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(102, 102, 102));
        emailTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailTxt.setText("jeffleivajr@estudiantec.cr");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(profileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        bg.add(profilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 290, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalInfoTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalInfoTxtMouseEntered
        generalInfoPanel.setBackground(new Color(168,168,168));
        generalInfoTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_generalInfoTxtMouseEntered

    private void generalInfoTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalInfoTxtMouseExited
        generalInfoPanel.setBackground(Color.white);
        generalInfoTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_generalInfoTxtMouseExited

    private void generalInfoPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalInfoPanelMouseEntered
        generalInfoPanel.setBackground(new Color(168,168,168));
        generalInfoTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_generalInfoPanelMouseEntered

    private void generalInfoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalInfoPanelMouseClicked

    }//GEN-LAST:event_generalInfoPanelMouseClicked

    private void generalInfoPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalInfoPanelMouseExited
        generalInfoPanel.setBackground(Color.white);
        generalInfoTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_generalInfoPanelMouseExited

    private void securityInfoPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_securityInfoPanelMouseEntered
        securityInfoPanel.setBackground(new Color(168,168,168));
        securityTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_securityInfoPanelMouseEntered

    private void securityInfoPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_securityInfoPanelMouseExited
        securityInfoPanel.setBackground(Color.white);
        securityTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_securityInfoPanelMouseExited

    private void deviceTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceTxtMouseEntered
         devicePanel.setBackground(new Color(168,168,168));
        deviceTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_deviceTxtMouseEntered

    private void deviceTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceTxtMouseExited
        devicePanel.setBackground(Color.white);
        deviceTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_deviceTxtMouseExited

    private void passTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseEntered
        passwordPanel.setBackground(new Color(168,168,168));
        passTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_passTxtMouseEntered

    private void passTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseExited
        passwordPanel.setBackground(Color.white);
        passTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_passTxtMouseExited

    private void passwordPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordPanelMouseEntered
        passwordPanel.setBackground(new Color(168,168,168));
        passTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_passwordPanelMouseEntered

    private void passwordPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPanelMousePressed

    private void passwordPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordPanelMouseExited
        passwordPanel.setBackground(Color.white);
        passTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_passwordPanelMouseExited

    private void devicePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devicePanelMouseEntered
        devicePanel.setBackground(new Color(168,168,168));
        deviceTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_devicePanelMouseEntered

    private void devicePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devicePanelMouseExited
        devicePanel.setBackground(Color.white);
        deviceTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_devicePanelMouseExited

    private void organizationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organizationPanelMouseEntered
        organizationPanel.setBackground(new Color(168,168,168));
        organizationTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_organizationPanelMouseEntered

    private void organizationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organizationPanelMouseExited
        organizationPanel.setBackground(Color.white);
        organizationTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_organizationPanelMouseExited

    private void configPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configPanelMouseEntered
        configPanel.setBackground(new Color(168,168,168));
        configTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_configPanelMouseEntered

    private void sessionPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sessionPanelMouseEntered
        sessionPanel.setBackground(new Color(168,168,168));
        sessionTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_sessionPanelMouseEntered

    private void configPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configPanelMouseExited
        configPanel.setBackground(Color.white);
        configTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_configPanelMouseExited

    private void sessionPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sessionPanelMouseExited
        sessionPanel.setBackground(Color.white);
        sessionTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_sessionPanelMouseExited

    private void applicationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationPanelMouseEntered
        applicationPanel.setBackground(new Color(168,168,168));
        appTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_applicationPanelMouseEntered

    private void applicationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationPanelMouseExited
        applicationPanel.setBackground(Color.white);
        appTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_applicationPanelMouseExited

    private void subPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subPanelMouseEntered
       subPanel.setBackground(new Color(168,168,168));
        subTxt.setForeground(new Color(0,120,212));
    }//GEN-LAST:event_subPanelMouseEntered

    private void subPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subPanelMouseExited
        subPanel.setBackground(Color.white);
        subTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_subPanelMouseExited

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitPanel.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitPanel.setBackground(new Color(240,240,240));
        exitTxt.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFinalAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFinalAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFinalAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFinalAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFinalAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountSettingsTxt;
    private javax.swing.JLabel appTxt;
    private javax.swing.JPanel applicationPanel;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel configPanel;
    private javax.swing.JLabel configTxt;
    private javax.swing.JPanel devicePanel;
    private javax.swing.JLabel deviceTxt;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel generalInfoPanel;
    private javax.swing.JLabel generalInfoTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel insideScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel optionHeaderPanel;
    private javax.swing.JPanel optionLateralPanel;
    private javax.swing.JPanel organizationPanel;
    private javax.swing.JLabel organizationTxt;
    private javax.swing.JLabel passTxt;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel pointTxt;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel profileTxt;
    private javax.swing.JLabel questionTxt;
    private javax.swing.JScrollPane scrollOnePane;
    private javax.swing.JPanel securityInfoPanel;
    private javax.swing.JLabel securityTxt;
    private javax.swing.JPanel sessionPanel;
    private javax.swing.JLabel sessionTxt;
    private javax.swing.JPanel subPanel;
    private javax.swing.JLabel subTxt;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
