/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeffrey Leiva
 */
public class FrameAccountRecuperation extends javax.swing.JFrame {

    /**
     * Creates new form FrameAccountRecuperation
     */
    public FrameAccountRecuperation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        firstLayerPanel = new javax.swing.JPanel();
        buttonSendEmail = new javax.swing.JPanel();
        sendEmailTxt = new javax.swing.JLabel();
        messageEmail = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        logoPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(231, 222, 217));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstLayerPanel.setBackground(new java.awt.Color(255, 255, 255));

        buttonSendEmail.setBackground(new java.awt.Color(40, 127, 195));
        buttonSendEmail.setForeground(new java.awt.Color(0, 153, 255));

        sendEmailTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        sendEmailTxt.setForeground(new java.awt.Color(255, 255, 255));
        sendEmailTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sendEmailTxt.setText("Enviar correo de recuperación");
        sendEmailTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendEmailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendEmailTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buttonSendEmailLayout = new javax.swing.GroupLayout(buttonSendEmail);
        buttonSendEmail.setLayout(buttonSendEmailLayout);
        buttonSendEmailLayout.setHorizontalGroup(
            buttonSendEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonSendEmailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sendEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buttonSendEmailLayout.setVerticalGroup(
            buttonSendEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonSendEmailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sendEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        messageEmail.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        messageEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageEmail.setText("Se enviará un correo de recuperación a esta dirección:");

        emailField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        emailField.setBorder(null);

        logoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoSoftware.png"))); // NOI18N

        javax.swing.GroupLayout firstLayerPanelLayout = new javax.swing.GroupLayout(firstLayerPanel);
        firstLayerPanel.setLayout(firstLayerPanelLayout);
        firstLayerPanelLayout.setHorizontalGroup(
            firstLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstLayerPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(firstLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageEmail))
                .addGap(29, 29, 29))
        );
        firstLayerPanelLayout.setVerticalGroup(
            firstLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstLayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        bg.add(firstLayerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendEmailTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendEmailTxtMouseClicked
        JOptionPane.showMessageDialog(bg, "Se ha enviado el correo");
    }//GEN-LAST:event_sendEmailTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAccountRecuperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAccountRecuperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAccountRecuperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAccountRecuperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAccountRecuperation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel buttonSendEmail;
    private javax.swing.JTextField emailField;
    private javax.swing.JPanel firstLayerPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoPanel;
    private javax.swing.JLabel messageEmail;
    private javax.swing.JLabel sendEmailTxt;
    // End of variables declaration//GEN-END:variables
}
